export const categories = [
  { slug: 'driver-essentials', name: 'Driver Essentials', description: 'Practical kit for long shifts: charging, mounting, visibility, comfort and weather protection.' },
  { slug: 'vehicle-van', name: 'Vehicle & Van', description: 'Cargo organisation, load protection, cleaning and everyday vehicle tools for delivery work.' },
  { slug: 'bike-ebike', name: 'Bike & E-bike', description: 'Courier equipment for urban riders, including weather, visibility, carrying and battery planning.' },
  { slug: 'food-delivery', name: 'Food Delivery', description: 'Thermal bags, spill control and workflow accessories for carrying food safely and efficiently.' },
  { slug: 'shipping-tools', name: 'Shipping Tools', description: 'Label printers, parcel scales and software for small online sellers that need a better dispatch workflow.' }
];

export const partnerPrograms = [
  { key: 'amazon', name: 'Amazon.ie Associates', audience: 'Drivers and small businesses buying physical gear', status: 'apply', verified: '2026-09-15', note: 'Useful for broad product coverage. Commission varies by category. Configure only after account approval.' },
  { key: 'sendcloud', name: 'Sendcloud Affiliate Programme', audience: 'Online retailers shipping parcels in Europe', status: 'apply', verified: '2026-09-15', note: 'Official programme advertises 100% on a referral’s first month, subject to its terms and qualification rules.' },
  { key: 'shipstation', name: 'ShipStation Affiliate Program', audience: 'Growing ecommerce sellers and operations teams', status: 'apply', verified: '2026-09-15', note: 'Official UK programme advertises fixed referral payouts by paid plan, subject to programme terms.' }
];

export const articles = [
  {
    slug: 'delivery-driver-starter-kit-ireland', title: 'Delivery Driver Starter Kit for Ireland: What Actually Matters on a Long Shift', description: 'A practical starter checklist for courier and delivery work in Ireland, prioritising reliability, weather protection and low-friction phone use.', category: 'driver-essentials', published: '2026-09-15', updated: '2026-09-15', intent: 'commercial', productQuery: 'delivery driver essentials',
    sections: [
      { heading: 'Start with failure points, not gadgets', paragraphs: ['A useful driver kit is less about owning a lot of accessories and more about removing the small failures that can interrupt a shift. The most common problems are predictable: a phone that cannot stay charged, a mount that moves when the road is rough, wet clothing, poor visibility in the dark, and loose items rolling around the vehicle.', 'For a first kit, spend on reliability before comfort upgrades. A dependable charging setup and a stable phone position affect almost every stop. Everything else can be added after a week of real use, when you know which problems are actually slowing you down.'], bullets: ['Stable phone mount that can be operated without blocking visibility', 'Fast car charger plus a spare cable', 'Compact power bank as backup rather than the primary power source', 'Waterproof outer layer and dry spare socks', 'Small torch or headlamp for dark addresses', 'Simple organiser for cables, pens and proof-of-delivery items'] },
      { heading: 'Build redundancy into power', paragraphs: ['Navigation, camera use, mobile data and bright screens are demanding. A single cable is therefore a weak point. Keep one main charging cable connected in the vehicle and one spare stored separately. If your phone supports fast charging, match the charger and cable to the phone’s supported charging standard rather than buying purely by the largest advertised wattage.', 'A power bank is most valuable when the vehicle socket fails, you spend time away from the vehicle, or you are riding a bike. It should be treated as backup capacity, not an excuse to begin a shift with a partly charged phone.'] },
      { heading: 'Weather protection is productivity equipment', paragraphs: ['Irish weather can change quickly enough that a jacket left at home becomes a work problem. A lightweight waterproof shell is easier to keep in the vehicle than a bulky coat, and layers underneath are more flexible across different temperatures.', 'Foot comfort matters because delivery work can combine driving with repeated short walks. Dry socks, supportive footwear and a change of shirt are unglamorous items, but they can have more effect on the second half of a shift than many electronic accessories.'] },
      { heading: 'Buy the first kit in stages', paragraphs: ['A sensible sequence is power and phone mounting first, then weather and visibility, then organisation. After that, add job-specific tools such as thermal bags, cargo straps or a parcel trolley only if your work actually needs them. This keeps the kit smaller, cheaper and easier to maintain.'] }
    ]
  },
  {
    slug: 'phone-mount-buying-guide-couriers', title: 'Phone Mount Buying Guide for Couriers: Stability, Reach and Heat Matter More Than Style', description: 'How to compare dashboard, windscreen and vent phone mounts for repeated navigation use without relying on marketing claims.', category: 'driver-essentials', published: '2026-09-15', updated: '2026-09-15', intent: 'commercial', productQuery: 'car phone mount strong',
    sections: [
      { heading: 'The best mount is the one you stop noticing', paragraphs: ['For delivery work, a phone mount is used far more often than in ordinary commuting. That changes the priorities. A courier needs a position that stays readable across hundreds of turns and repeated stops, can be reached without stretching, and does not loosen every few days.', 'Avoid choosing solely by the strength of a magnet or the size of a suction cup. The complete system matters: mounting surface, arm length, hinge stiffness, phone case, vibration and the temperature inside the vehicle.'] },
      { heading: 'Choose the mounting position first', paragraphs: ['A windscreen mount can offer flexible positioning but must not obstruct the driver’s view. A dashboard mount can be lower and visually cleaner if the surface is suitable. Vent mounts are compact, but some vents flex under the weight of larger phones and airflow can heat or cool the device directly.', 'Before buying, sit in your normal driving position and identify a location that keeps navigation visible with minimal eye movement while preserving a clear field of view and access to controls. Local road-safety rules and vehicle-specific restrictions take priority.'] },
      { heading: 'Shorter arms usually move less', paragraphs: ['Long articulated arms can place the phone exactly where you want it, but each joint adds leverage and another point that can vibrate. For rough urban roads, a shorter rigid mounting path is generally easier to keep stable.', 'If you use wireless charging, check heat as well as convenience. Navigation and a bright screen already warm a phone; wireless charging can add more heat. A wired charger may be more predictable during long shifts.'] },
      { heading: 'A simple comparison checklist', bullets: ['One-handed insertion and removal', 'No interference with visibility, airbags or controls', 'Fits the phone with its normal case', 'Does not sag under the phone’s weight', 'Charging cable can connect without sharp bends', 'Replacement pads or parts are available'], paragraphs: ['Treat the mount as a work tool. If it needs constant tightening or forces awkward movement, replace it even if it still technically holds the phone.'] }
    ]
  },
  {
    slug: 'power-bank-capacity-delivery-shifts', title: 'How Much Power Bank Capacity Does a Delivery Driver Need?', description: 'A practical way to estimate backup battery needs for navigation-heavy work without buying an unnecessarily large power bank.', category: 'driver-essentials', published: '2026-09-15', updated: '2026-09-15', intent: 'commercial', productQuery: 'usb c power bank 20000mah fast charge',
    sections: [
      { heading: 'Capacity numbers are not the whole story', paragraphs: ['Power banks are usually advertised in milliamp-hours, but the useful energy that reaches a phone is lower than the headline number because voltage conversion and charging create losses. Instead of assuming that a 10,000 mAh bank gives a fixed number of full phone charges, use it as a rough size class.', 'For vehicle drivers with reliable in-car charging, a compact bank may be enough as emergency redundancy. Bike couriers or workers who spend long periods away from a powered vehicle need more reserve.'] },
      { heading: 'Estimate from your worst realistic shift', paragraphs: ['Start with the phone battery size and observe how much battery a demanding shift consumes when you are not charging. If a full shift would consume roughly one and a half phone batteries, size your backup to cover that demand with margin rather than simply buying the largest bank available.', 'A larger bank brings weight and longer recharge time. For riders, that matters every day. Two medium batteries can also offer redundancy, but they create more items to remember and recharge.'] },
      { heading: 'Charging speed and ports are often more important', bullets: ['USB-C input and output if your phone supports it', 'A charging protocol compatible with your phone', 'Enough output while another device is connected, if multi-device use matters', 'Clear battery-level indication', 'A reputable battery manufacturer and appropriate safety certifications'], paragraphs: ['Fast recharging during a short break can be more useful than carrying unused capacity. Match the bank to your actual device rather than assuming a higher wattage label automatically means faster charging.'] },
      { heading: 'Keep batteries out of extreme heat', paragraphs: ['Do not leave lithium battery packs on a hot dashboard or in other high-temperature locations. Inspect cables and the battery casing periodically, and stop using any pack that is swollen, damaged or behaving abnormally.'] }
    ]
  },
  {
    slug: 'rain-gear-delivery-drivers-ireland', title: 'Rain Gear for Delivery Drivers in Ireland: A Layering Checklist That Fits in the Vehicle', description: 'A compact rain and cold-weather setup for drivers and couriers who need protection without carrying a wardrobe.', category: 'driver-essentials', published: '2026-09-15', updated: '2026-09-15', intent: 'commercial', productQuery: 'waterproof jacket hi vis delivery driver',
    sections: [
      { heading: 'Think in layers, not one heavy coat', paragraphs: ['A single insulated waterproof coat can be too warm when moving parcels and too bulky to store. A shell-and-layer approach is more flexible: a waterproof outer shell for rain and wind, an insulating layer for cold periods, and a breathable base layer next to the skin.', 'For vehicle-based delivery, packability matters. A shell that lives permanently in the van is more useful than an excellent jacket that is often left at home.'] },
      { heading: 'Keep the dry items boring and reliable', bullets: ['Waterproof shell with a hood that does not block peripheral vision', 'Spare socks sealed in a small bag', 'Lightweight gloves that still allow safe device use', 'A small towel or cloth for wet hands and equipment', 'High-visibility outer layer when required by the work environment'], paragraphs: ['Water resistance degrades with wear and washing. Follow the garment manufacturer’s care instructions and renew water repellency when appropriate instead of assuming a jacket will perform the same forever.'] },
      { heading: 'Footwear deserves its own decision', paragraphs: ['A waterproof shoe is not automatically comfortable for repeated entry and exit from a vehicle. Look for grip, fit and support first, then weather resistance. If footwear becomes soaked, having dry socks and a second pair available can be more practical than expecting one pair to handle every condition.'] },
      { heading: 'Do not trade visibility for weather protection', paragraphs: ['Hoods, hats and fogged eyewear can reduce awareness. Adjust clothing so that your field of vision and hearing remain adequate around traffic, loading bays and driveways. The safest kit is the one that protects you without creating a new hazard.'] }
    ]
  },
  {
    slug: 'thermal-delivery-bag-guide', title: 'Thermal Delivery Bags: What to Check Before Buying One', description: 'A specification-first guide to thermal food bags covering size, cleanability, structure and everyday handling.', category: 'food-delivery', published: '2026-09-15', updated: '2026-09-15', intent: 'commercial', productQuery: 'insulated food delivery bag waterproof',
    sections: [
      { heading: 'Insulation is only one part of the job', paragraphs: ['A food-delivery bag needs to preserve temperature, but it also needs to survive frequent opening, carry awkward packaging and be easy to clean. Thick insulation is not useful if the zipper fails, the base collapses, or spills soak into material that cannot be wiped properly.', 'Start by measuring the order types you expect to carry. A very large bag is flexible, but it can allow small orders to slide around unless it has dividers or internal structure.'] },
      { heading: 'Look at structure and cleaning', bullets: ['A stable base that stays reasonably flat when carried', 'Wipe-clean internal surfaces', 'Strong handles and shoulder straps with reinforced stitching', 'Zippers that can be operated repeatedly with gloves', 'Internal dividers if drinks and food need separation', 'Reflective details if the bag will be used by riders at night'], paragraphs: ['For liquids, the bag cannot replace secure restaurant packaging. Keep containers upright and use internal separators where practical.'] },
      { heading: 'Backpack versus box-style bag', paragraphs: ['Backpack bags make sense for riders because carrying weight close to the body is important. Box-style bags can work well in cars because they stay upright on a seat or in a boot and can be moved with two handles.', 'The correct format therefore depends more on transport method and order shape than on advertised litre capacity alone.'] },
      { heading: 'Clean after the shift, not after the smell appears', paragraphs: ['Wipe spills promptly, allow the bag to dry fully, and follow any food-hygiene requirements that apply to your work. Inspect seams, lining and closures. A damaged bag can become harder to clean and less effective at maintaining temperature.'] }
    ]
  },
  {
    slug: 'van-cargo-organisation-delivery', title: 'Van Cargo Organisation for Delivery Work: Reduce Searching Before You Add More Shelves', description: 'A workflow-first approach to organising parcels, tools and consumables in a small delivery van.', category: 'vehicle-van', published: '2026-09-15', updated: '2026-09-15', intent: 'commercial', productQuery: 'van cargo organiser storage bins straps',
    sections: [
      { heading: 'Organisation starts with a retrieval rule', paragraphs: ['A van can look tidy and still waste time if there is no consistent rule for where the next item goes. Before buying shelves, bins or organisers, decide how items will be grouped: by route sequence, delivery zone, parcel size or another method that matches the work.', 'The goal is not maximum storage density. The goal is predictable retrieval without unstable stacking or unnecessary movement inside the load area.'] },
      { heading: 'Use containers to create zones', paragraphs: ['Simple crates or soft organisers can separate small parcels, paperwork, cleaning items and personal equipment. Clear labels help when more than one person uses the vehicle. Avoid loose heavy objects that can move under braking.', 'Any cargo restraint must be suitable for the load and used in accordance with vehicle, equipment and road-safety requirements. This guide is about organisation, not a substitute for professional load-securing guidance.'] },
      { heading: 'Protect the loading surface', bullets: ['Non-slip matting where appropriate', 'Moving blankets for items that can scratch', 'Dedicated container for straps so they are not tangled', 'A small waste container to prevent packaging debris spreading', 'A separate clean zone for food or personal items'], paragraphs: ['A clean load area makes missing or damaged equipment easier to notice and reduces the chance that dirt transfers to customer items.'] },
      { heading: 'Review the layout after real routes', paragraphs: ['If you repeatedly move one box to reach another, the layout is telling you something. Make small changes based on recurring friction instead of installing a permanent system before the workflow is understood.'] }
    ]
  },
  {
    slug: 'dash-cam-guide-delivery-drivers', title: 'Dash Cam Buying Guide for Delivery Drivers: Reliability Before Resolution', description: 'What delivery drivers should compare in a dash cam, including power, storage, heat tolerance and parking features.', category: 'vehicle-van', published: '2026-09-15', updated: '2026-09-15', intent: 'commercial', productQuery: 'dash cam front rear parking mode high endurance card',
    sections: [
      { heading: 'A dash cam is a reliability product', paragraphs: ['Very high video resolution is easy to market, but a camera that fails to record when storage is full, power is interrupted or temperature rises is not useful. For delivery vehicles, frequent starts and stops make power behaviour and automatic recording especially important.', 'Prioritise stable loop recording, clear timestamps, easy status checks and a memory card that is suitable for repeated video writing.'] },
      { heading: 'Front-only or front and rear', paragraphs: ['A front camera is simpler and usually easier to install. A rear camera adds coverage but also adds wiring and another component that must remain clean and correctly positioned. Decide based on the vehicle and the risks you actually want recorded.', 'Parking mode may require a hardwire kit or another power arrangement. Installation should not interfere with vehicle safety systems, visibility or manufacturer requirements.'] },
      { heading: 'Storage is part of the system', bullets: ['Check the camera’s supported card type and maximum capacity', 'Use high-endurance storage intended for continuous recording when recommended', 'Format and replace cards according to the manufacturer’s guidance', 'Confirm regularly that new files are actually being written'], paragraphs: ['Do not wait for an incident to discover that the card stopped recording weeks earlier. A quick periodic playback check is more valuable than trusting a status light indefinitely.'] },
      { heading: 'Respect privacy and workplace rules', paragraphs: ['Recording public roads, customer locations, passengers or audio can create privacy and employment considerations. Use the camera in line with applicable law, employer policies and any notice requirements relevant to your situation.'] }
    ]
  },
  {
    slug: 'ebike-courier-gear-checklist', title: 'E-bike Courier Gear Checklist: Carry Less, Protect the Essentials', description: 'A lightweight equipment checklist for e-bike couriers focused on visibility, weather, power and secure carrying.', category: 'bike-ebike', published: '2026-09-15', updated: '2026-09-15', intent: 'commercial', productQuery: 'bike courier waterproof gear lights phone mount',
    sections: [
      { heading: 'Every extra item is carried all day', paragraphs: ['Vehicle drivers can keep backup equipment in a boot. A rider pays for every unnecessary item in weight and bulk, so the kit should be deliberately small. Prioritise equipment that solves high-impact failures: visibility, punctures, phone power, weather and secure carrying.', 'The bike itself must be maintained separately from the delivery kit. Brakes, tyres, lights and battery condition are safety-critical and should follow the manufacturer’s maintenance guidance.'] },
      { heading: 'Protect phone power from weather', paragraphs: ['Navigation can drain a phone quickly, but exposed charging cables and rain are a poor combination. Use weather-appropriate equipment and avoid charging arrangements that compromise the phone’s water protection. A protected power bank inside the bag can be useful when safely connected.', 'A phone mount should hold the device firmly without forcing the rider to look down for long periods. Route changes should be handled only when it is safe to do so.'] },
      { heading: 'The compact essentials', bullets: ['Compliant front and rear lights plus backup visibility', 'Waterproof shell and compact over-trousers if needed', 'Basic puncture solution appropriate to the bike', 'Small pump or inflator compatible with the tyres', 'Power bank and short durable cable', 'Secure lock appropriate to the parking risk', 'Insulated delivery bag if carrying food'], paragraphs: ['Local legal requirements for lighting, e-bikes and road use take priority over any generic gear list.'] },
      { heading: 'Separate work cargo from repair items', paragraphs: ['Tools can be dirty or sharp. Keep them in a small dedicated pouch so they do not damage food packaging, clothing or electronics. A repeatable packing layout also makes it obvious when something has been forgotten.'] }
    ]
  },
  {
    slug: 'label-printer-parcel-scale-home-business', title: 'Label Printer and Parcel Scale Setup for a Small Online Seller', description: 'A simple dispatch-station setup for home and micro ecommerce businesses that want fewer manual shipping errors.', category: 'shipping-tools', published: '2026-09-15', updated: '2026-09-15', intent: 'commercial', productQuery: 'thermal label printer parcel scale ecommerce',
    sections: [
      { heading: 'The goal is one repeatable dispatch flow', paragraphs: ['A small seller does not need warehouse automation to benefit from a dedicated packing station. The biggest improvement often comes from keeping weighing, label creation, printing and final parcel checks in one consistent sequence.', 'A thermal label printer can remove ink from the process, but only if it supports the label sizes and computer or mobile workflow used by your carriers or shipping software.'] },
      { heading: 'Choose the scale for the parcels you really send', paragraphs: ['Maximum weight is only one specification. Platform size, display readability and graduation matter too. If large boxes hide the display, a scale with a separate display can be easier to use. For small parcels, fine measurement increments may matter more than a very high maximum capacity.', 'Carrier billing can depend on dimensions as well as weight, so keep a measuring tool at the station and record dimensions consistently when required.'] },
      { heading: 'Printer questions before purchase', bullets: ['Which label size does your carrier workflow use?', 'Does the printer support your operating system and connection method?', 'Can you obtain compatible labels easily?', 'Is automatic label calibration reliable?', 'Will several people need to print from different devices?'], paragraphs: ['Do not buy a printer solely because it is described as a shipping printer. Confirm the exact workflow from order platform to shipping software to final label.'] },
      { heading: 'Create a final-check zone', paragraphs: ['Place completed parcels in a separate area only after address, service and packaging checks are complete. Physical separation between “still processing” and “ready for collection” reduces accidental duplicate labels and missed parcels.'] }
    ]
  },
  {
    slug: 'sendcloud-vs-shipstation-europe', title: 'Sendcloud vs ShipStation for a Small European Ecommerce Business', description: 'A neutral framework for comparing two shipping platforms based on carriers, workflow, integrations and operating complexity.', category: 'shipping-tools', published: '2026-09-15', updated: '2026-09-15', intent: 'commercial-software', productQuery: null,
    sections: [
      { heading: 'Start with your carrier workflow, not the brand name', paragraphs: ['Shipping software is valuable when it removes repetitive work between the online store, carrier labels, tracking and returns. The right platform depends on where you sell, which carriers you use, order volume, team size and whether you need advanced automation.', 'Before comparing features, write down the current dispatch process from paid order to collected parcel. The steps that create manual copying, repeated logins or frequent errors are the ones a platform should eliminate.'] },
      { heading: 'Where Sendcloud may fit', paragraphs: ['Sendcloud is strongly positioned around European ecommerce shipping and promotes integrations, carrier connections, tracking and returns. Its affiliate programme is also aimed at ecommerce content creators and software review sites, which makes the platform relevant to DROPi Delivery’s small-business audience.', 'A seller should still verify support for the exact origin country, carriers, services and store integration they use before choosing a paid plan.'] },
      { heading: 'Where ShipStation may fit', paragraphs: ['ShipStation serves a broad ecommerce shipping market and promotes order management, rate comparison, label creation and scaling fulfillment. Its plan structure and available carrier integrations can make sense for businesses that want a central shipping console across multiple selling channels.', 'As with any shipping platform, the useful comparison is not the longest feature list. It is how many manual steps disappear for your specific order flow.'] },
      { heading: 'Run a controlled trial', bullets: ['Connect one sales channel first', 'Test the carriers and services you use most', 'Print real test labels where permitted', 'Check address correction and failed-order handling', 'Test customer notifications and returns workflow', 'Measure time per order before and after'], paragraphs: ['Do not switch every process at once. A short controlled trial gives better evidence than feature-table comparisons and makes it easier to identify hidden workflow changes.'] }
    ]
  },
  {
    slug: 'delivery-car-cleaning-kit', title: 'A Minimal Cleaning Kit for a Delivery Car or Van', description: 'A compact cleaning setup for keeping a work vehicle presentable without carrying unnecessary chemicals and equipment.', category: 'vehicle-van', published: '2026-09-15', updated: '2026-09-15', intent: 'commercial', productQuery: 'car cleaning kit microfiber interior delivery van',
    sections: [
      { heading: 'Clean enough to protect the work', paragraphs: ['A delivery vehicle does not need to look detailed every day, but dirt, packaging waste and spilled liquids can damage customer items and make the load area harder to manage. A small kit kept in one container is more likely to be used than a collection of products spread around the vehicle.', 'Separate products used in the cab from anything used around food-delivery bags or customer goods. Follow product labels and workplace hygiene rules.'] },
      { heading: 'A small kit is usually sufficient', bullets: ['Microfibre cloths in two clearly separated uses', 'Small waste bags', 'Soft brush for dry dirt', 'Suitable interior cleaner used according to its label', 'Paper towel or absorbent cloth for spills', 'Hand-cleaning supplies appropriate to the job'], paragraphs: ['Avoid storing leaking bottles loose in the load area. Keep liquids upright in a closed container and protect them from temperature extremes where required by the manufacturer.'] },
      { heading: 'Use a five-minute reset', paragraphs: ['At the end of a route, remove waste, return straps and tools to their places, wipe obvious spills and check the cab for items needed tomorrow. A short consistent reset prevents a large cleaning job from building up.', 'The same routine doubles as an equipment check. Missing chargers, damaged bags and worn straps are easier to notice when the vehicle is reset to a standard layout.'] }
    ]
  },
  {
    slug: 'parcel-trolley-hand-truck-buying-guide', title: 'Parcel Trolley and Folding Hand Truck Buying Guide', description: 'How to choose a compact trolley for boxes and delivery work based on load shape, wheels, platform size and storage.', category: 'vehicle-van', published: '2026-09-15', updated: '2026-09-15', intent: 'commercial', productQuery: 'folding hand truck parcel trolley',
    sections: [
      { heading: 'Rated capacity is not the same as practical capacity', paragraphs: ['A trolley may have a high load rating but still be awkward with a tall, unstable stack or a box wider than its platform. Consider the shape and dimensions of typical loads, not only kilograms.', 'For urban delivery, kerbs, uneven paving and steps may matter more than the headline load rating. Larger wheels generally handle rough surfaces better, but they also take more space in a small vehicle.'] },
      { heading: 'Folding mechanisms trade space for complexity', paragraphs: ['A compact folding trolley is attractive when it must live behind a seat or against the van wall. Check whether the handle and wheels lock positively in working position and whether the mechanism can be operated without trapping fingers.', 'The best folding design is one you will actually deploy for a short walk rather than deciding it is too awkward and carrying the boxes instead.'] },
      { heading: 'Check these dimensions', bullets: ['Platform width and depth', 'Handle height when extended', 'Folded size', 'Wheel diameter', 'Trolley weight', 'Manufacturer-rated maximum load'], paragraphs: ['Stay within the manufacturer’s rated limits and use safe manual-handling practices. A trolley reduces carrying, but it does not make an unstable or excessive load safe.'] }
    ]
  }
];

export function getArticle(slug) { return articles.find((article) => article.slug === slug); }
